title: "Homework 09: Project Part II: Analysis Write-Up"
theme: jekyll-theme-cayman  # or jekyll-theme-midnight
description: "Exploring the relationship between presidential administrations, economic growth, and S&P 500 performance"




